---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: notebooks-e2e-test
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: List of components in the group
      name: group-components
      type: string
  tasks:
    - name: generate-snapshot
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      workspaces:
      - name: basic-auth
        workspace: git-auth
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
        - name: revision
          value: odh
        - name: pathInRepo
          value: konflux-tekton-tasks/generate-snapshot-for-group-testing/0.1/generate-snapshot-for-group-testing.yaml
    - name: audit-snapshot
      runAfter:
        - generate-snapshot
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      taskSpec:
        params:
          - name: COMPONENTS
            description: List of components in the group
        steps:
          - name: audit-snapshot
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
              - name: COMPONENTS
                value: $(params.COMPONENTS)
            script: |
              #!/bin/bash
              set -e
              echo "SNAPSHOT=${SNAPSHOT}"

              # Parse JSON and iterate through each component
              while IFS= read -r row; do
                  COMPONENT_NAME=$(echo "$row" | base64 -d | jq -r '.key')
                  IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
                  GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
                  GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
                  echo "${COMPONENT_NAME} IMAGE: ${IMAGE}"
                  echo "GIT_COMMIT=${GIT_COMMIT}"
                  echo "GIT_URL=${GIT_URL}"
              done < <(echo "$COMPONENTS" | jq -r 'to_entries[] | @base64')
    - name: provision-eaas-space
      runAfter:
        - audit-snapshot
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.2xlarge

    - name: deploy-and-test
      runAfter:
        - provision-cluster
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: e2e-jupyter-minimal-ubi9-python-3-12
            image: quay.io/rhoai/rhoai-task-toolset:notebooks
            env:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
            workingDir: /workspace/source
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              oc get pods
              oc whoami
              
              COMPONENT_NAME=odh-workbench-jupyter-datascience-cpu-py312-ubi9-ci
              JUPYTER_DATA_SCIENCE_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
              echo "  JUPYTER_DATA_SCIENCE_IMAGE: ${JUPYTER_DATA_SCIENCE_IMAGE"
              echo "GIT_COMMIT=${GIT_COMMIT}"
              echo "GIT_URL=${GIT_URL}"

              REPO_URL=${GIT_URL}
              REVISION=${GIT_COMMIT}

              echo "REPO_URL=${REPO_URL}"
              echo "REVISION=${REVISION}"
              git clone "${REPO_URL}" src_code
              cd src_code
              git checkout ${REVISION}
              
              oc new-project jupyter-datascience-ubi9-python-3-12
              IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_DATA_SCIENCE_IMAGE}"
              make deploy9-jupyter-datascience-ubi9-python-3.12 \
                  -e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
              make test-jupyter-datascience-ubi9-python-3.12
              make undeploy9-jupyter-datascience-ubi9-python-3.12


    #       - name: cuda-jupyter-pt-ubi9-python-3-12-test-e2e
    #         image: quay.io/rhoai/rhoai-task-toolset:notebooks
    #         env:
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         workingDir: /workspace/source
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         script: |
    #           oc new-project jupyter-pytorch-ubi9-python-3-12
    #           IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_PYTORCH_IMAGE}"
    #           make deploy9-jupyter-pytorch-ubi9-python-3.12 \
    #               -e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
    #           make test-jupyter-pytorch-ubi9-python-3.12
    #           make undeploy9-jupyter-pytorch-ubi9-python-3.12

    #       - name: cuda-jupyter-ubi9-python-3-12-test-e2e
    #         image: quay.io/rhoai/rhoai-task-toolset:notebooks
    #         env:
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         workingDir: /workspace/source
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         script: |
    #           oc new-project cuda-jupyter-minimal-ubi9-python-3-12
    #           IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_MINIMAL_IMAGE}"
    #           make deploy9-cuda-jupyter-minimal-ubi9-python-3.12 \
    #               -e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
    #           make test-cuda-jupyter-minimal-ubi9-python-3.12
    #           make undeploy9-cuda-jupyter-minimal-ubi9-python-3.12

    #       - name: cuda-jupyter-tf-ubi9-python-3-12-test-e2e
    #         image: quay.io/rhoai/rhoai-task-toolset:notebooks
    #         env:
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         workingDir: /workspace/source
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         script: |
    #           oc new-project cuda-jupyter-tensorflow-ubi9-python-3-12
    #           IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_TENSORFLOW_IMAGE}"
    #           make deploy9-cuda-jupyter-tensorflow-ubi9-python-3.12 \
    #               -e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
    #           make test-cuda-jupyter-tensorflow-ubi9-python-3.12
    #           make undeploy9-cuda-jupyter-tensorflow-ubi9-python-3.12

    #       - name: jupyter-tai-ubi9-python-3-12-test-e2e
    #         image: quay.io/rhoai/rhoai-task-toolset:notebooks
    #         env:
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         workingDir: /workspace/source
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         script: |
    #           oc new-project jupyter-trustyai-ubi9-python-3-12
    #           IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_TRUSTYAI_IMAGE}"
    #           make deploy9-jupyter-trustyai-ubi9-python-3.12 \
    #               -e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
    #           make test-jupyter-trustyai-ubi9-python-3.12
    #           make undeploy9-jupyter-trustyai-ubi9-python-3.12

    
    #       - name: create-cluster
    #         ref:
    #           resolver: git
    #           params:
    #             - name: url
    #               value: https://github.com/konflux-ci/build-definitions.git
    #             - name: revision
    #               value: main
    #             - name: pathInRepo
    #               value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
    #         params:
    #           - name: eaasSpaceSecretRef
    #             value: $(tasks.provision-eaas-space-llmisvc.results.secretRef)
    #           - name: version
    #             value: "$(steps.pick-version.results.version)"
    #           - name: instanceType
    #             value: m5.2xlarge

    # - name: rocm-notebooks-py312-e2e-tests
    #   runAfter:
    #     - provision-cluster-llmisvc
    #   params:
    #   - name: git-url
    #     value: "$(tasks.parse-metadata.results.source-git-url)"
    #   - name: git-rev
    #     value: "$(tasks.parse-metadata.results.target-git-branch)"
    #   - name: component-image
    #     value: "$(tasks.parse-metadata.results.component-container-image)"
    #   taskSpec:
    #     params:
    #       - name: git-url
    #         type: string
    #       - name: git-rev
    #         type: string
    #       - name: component-image
    #         type: string
    #     volumes:
    #       - name: credentials
    #         emptyDir: {}
    #     steps:
    #       - name: get-kubeconfig
    #         ref:
    #           resolver: git
    #           params:
    #             - name: url
    #               value: https://github.com/konflux-ci/build-definitions.git
    #             - name: revision
    #               value: main
    #             - name: pathInRepo
    #               value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
    #         params:
    #           - name: eaasSpaceSecretRef
    #             value: $(tasks.provision-eaas-space-llmisvc.results.secretRef)
    #           - name: clusterName
    #             value: "$(tasks.provision-cluster-llmisvc.results.clusterName)"
    #           - name: credentials
    #             value: credentials

    #       - name: clone-repo
    #         image: alpine/git
    #         script: |
    #           echo $(params.git-url)
    #           echo $(params.git-rev)
    #           git clone --depth 1 --branch $(params.git-rev) $(params.git-url) /workspace/source
    #           git config --global --add safe.directory /workspace/source
    #           cd /workspace/source
              
    #       - name: rocm-jupyter-pt-ubi9-python-3-12-test-e2e
    #         image: quay.io/rhoai/rhoai-task-toolset:notebooks
    #         env:
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         workingDir: /workspace/source
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         script: |
    #           oc new-project rocm-jupyter-pytorch-python-3-12
    #           IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_rocm__PYTORCH_IMAGE}"
    #           make deploy9-jupyter-rocm-pytorch-ubi9-python-3.12 \
    #               -e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
    #           make test-jupyter-rocm-pytorch-ubi9-python-3.12
    #           make undeploy9-jupyter-rocm-pytorch-ubi9-python-3.12
  workspaces:
  - name: git-auth
    optional: true
