---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: opendatahub-operator-e2e-test
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: find-component-image
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      runAfter:
        - parse-metadata
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        steps:
        - image: quay.io/konflux-ci/konflux-test:stable
          workingDir: /workspace
          env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            - name: COMPONENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['appstudio.openshift.io/component']
          script: |
            #!/bin/sh

            # Extract the component container image from the SNAPSHOT JSON data
            COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")

            # Log the extracted variable
            echo "  COMPONENT_CONTAINER_IMAGE: ${COMPONENT_CONTAINER_IMAGE}"
    - name: check-prerequisites
      description: check prerequisites if the ITS needs to execute
      runAfter:
        - find-component-image
      taskSpec:
        results:
        - name: event-type
          description: "stores info about event type"
        steps:
        - image: quay.io/konflux-ci/konflux-test:stable
          env:
            - name: EVENT_TYPE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['pac.test.appstudio.openshift.io/event-type']
          script: |
            #!/bin/bash
            set -e
            echo "EVENT_TYPE=${EVENT_TYPE}"
            echo -n "${EVENT_TYPE}" > $(results.event-type.path)
    - name: provision-eaas-space
      runAfter:
        - check-prerequisites
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
      when:
        - input: "$(tasks.check-prerequisites.results.event-type)"
          operator: in
          values: ["pull_request", "retest-all-comment", "on-comment"]

    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.2xlarge
      when:
        - input: "$(tasks.check-prerequisites.results.event-type)"
          operator: in
          values: ["pull_request", "retest-all-comment", "on-comment"]
    - name: deploy-and-test
      runAfter:
        - provision-cluster
      params:
      - name: git-url
        value: "$(tasks.parse-metadata.results.source-git-url)"
      - name: git-rev
        value: "$(tasks.parse-metadata.results.target-git-branch)"
      - name: namespace
        value: "$(params.NAMESPACE)"
      - name: operator-image
        value: "$(tasks.parse-metadata.results.component-container-image)"
      taskSpec:
        params:
          - name: git-url
            type: string
          - name: git-rev
            type: string
          - name: namespace
            type: string
          - name: operator-image
            type: string
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials

          - name: clone-repo
            image: alpine/git
            script: |
              echo $(params.git-url)
              echo $(params.git-rev)
              git clone --depth 1 --branch $(params.git-rev) $(params.git-url) /workspace/source
              git config --global --add safe.directory /workspace/source
              cd /workspace/source

          - name: e2e-odh-kserve
            image: golang:1.25-alpine
            env:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
            workingDir: /workspace/source
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              set -euxo pipefail
              apk add --no-cache bash make git curl \
              && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
              && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
              && rm kubectl

              echo "ODH_MODEL_CONTROLLER_IMAGE=${ODH_MODEL_CONTROLLER_IMAGE}"

              git clone https://github.com/opendatahub-io/kserve.git /tmp/kserve
              pushd /tmp/kserve
                git fetch --all --tags
                git checkout release-v0.15

                export GITHUB_SHA="${PULL_BASE_SHA:-stable}"
                export ODH_MODEL_CONTROLLER_IMAGE="${ODH_MODEL_CONTROLLER_IMAGE}"

                echo "Loading environment variables from params.env"
                #Parse params.env into shell vars with underscores instead of dashes
                while IFS='=' read -r key value; do
                  case "$key" in
                    ''|\#*) continue ;;
                  esac
                  key="${key%%[[:space:]]*}"
                  value="${value##[[:space:]]}"
                  sane_key="${key//-/_}"
                  printf -v "$sane_key" '%s' "$value"
                done < config/overlays/odh/params.env

                export KSERVE_CONTROLLER_IMAGE="${kserve_controller}"
                export KSERVE_AGENT_IMAGE="${kserve_agent}"
                export KSERVE_ROUTER_IMAGE="${kserve_router}"
                export KSERVE_STORAGE_INITIALIZER_IMAGE="${kserve_storage_initializer}"
                export LLMD_IMAGE="${kserve_llm_d}"
                export LLMD_INFERENCE_SCHEDULER_IMAGE="${kserve_llm_d_inference_scheduler}"
                export LLMD_ROUTING_SIDECAR_IMAGE="${kserve_llm_d_routing_sidecar}"
                export KUBE_RBAC_PROXY_IMAGE="${kube_rbac_proxy}"

                echo "Loaded all images from params.env:"
                echo "KSERVE_CONTROLLER_IMAGE=${KSERVE_CONTROLLER_IMAGE}"
                echo "KSERVE_AGENT_IMAGE=${KSERVE_AGENT_IMAGE}"
                echo "KSERVE_ROUTER_IMAGE=${KSERVE_ROUTER_IMAGE}"
                echo "KSERVE_STORAGE_INITIALIZER_IMAGE=${KSERVE_STORAGE_INITIALIZER_IMAGE}"
                echo "LLMD_IMAGE=${LLMD_IMAGE}"
                echo "LLMD_INFERENCE_SCHEDULER_IMAGE=${LLMD_INFERENCE_SCHEDULER_IMAGE}"
                echo "LLMD_ROUTING_SIDECAR_IMAGE=${LLMD_ROUTING_SIDECAR_IMAGE}"
                echo "KUBE_RBAC_PROXY_IMAGE=${KUBE_RBAC_PROXY_IMAGE}"

                ./test/scripts/openshift-ci/run-e2e-tests.sh raw 2 raw
              popd
      when:
        - input: "$(tasks.check-prerequisites.results.event-type)"
          operator: in
          values: ["pull_request", "retest-all-comment", "on-comment"]
