---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: trigger-nightly-
  namespace: open-data-hub-tenant
spec:
  taskRunTemplate:
    serviceAccountName: odh-nightly-sa
  pipelineSpec:
    description: |
      Tags the latest CI build as a nightly and then triggers tests, slack notification
    params:
      - description: Snapshot of the application
        name: SNAPSHOT
        type: string
      - description: FBC image source
        name: CATALOG_IMAGE
        type: string
        default: quay.io/opendatahub/opendatahub-operator-catalog:odh-stable
      - description: Trigger Nightly Tests
        name: TRIGGER_NIGHTLY_TESTS
        type: string
        default: "false"
      - description: Trigger Slack Notification
        name: TRIGGER_SLACK
        type: string
        default: "true"
      - description: Whether to tag the latest CI build as a nightly
        name: TRIGGER_NIGHTLY_TAG
        type: string
        default: "true"
    tasks:
      - name: choose-ci-build
        description: selects the latest ci build to promote to nightly
        taskSpec:
          results:
          - name: latest-catalog-ci-image
            description: "the catalog image reference (with SHA) to use for nightly"
          - name: latest-build-metadata-url
            description: "the operator image reference (with SHA) to use for nightly"
          - name: latest-catalog-ci-build-url
            description: "the build url for the latest catalog"
          steps:
          - image: quay.io/rhoai/rhoai-task-toolset:odh-nightly-runner
            name: get-latest-catalog-ci-build-sha
            env:
            - name: HOME
              value: /workspace
            - name: CATALOG_IMAGE
              value: $(params.CATALOG_IMAGE)
            script: |
              #!/bin/bash
              set -e
              skopeo_inspect=$(skopeo inspect "docker://$CATALOG_IMAGE" --no-tags)
              echo "$skopeo_inspect" | jq -r '.Name + "@" + .Digest' | tr -d '\n' | tee "$(results.latest-catalog-ci-image.path)"
              echo "$skopeo_inspect" | jq -r '.Labels."build-metadata-url"'  | tr -d '\n' | tee "$(results.latest-build-metadata-url.path)"
              echo "$skopeo_inspect" | jq -r '.Labels."build-url"'  | tr -d '\n' | tee "$(results.latest-catalog-ci-build-url.path)"
      - name: tag-nightly
        runAfter:
        - choose-ci-build
        description: Tags the latest ci build as nightly
        workspaces:
        - name: data
          workspace: data
        taskSpec:
          workspaces:
            - name: data
              optional: false
          steps:
          - image: $(tasks.choose-ci-build.results.latest-catalog-ci-image)
            name: get-current-catalog
            env:
            - name: HOME
              value: /workspace
            - name: DATA_PATH
              value: $(workspaces.data.path)
            script: |
              #!/bin/sh
              cp -r /configs/* "$DATA_PATH"/
              if ! ls "$DATA_PATH"/rhods-operator/catalog.yaml; then
                echo "Error: catalog not found"
                exit 1
              fi
          - image: quay.io/rhoai/rhoai-task-toolset:odh-nightly-runner
            name: tag-nightly-images
            workingDir: /workspace
            env:
            - name: HOME
              value: /workspace
            - name: CATALOG_IMAGE
              value: $(params.CATALOG_IMAGE)
            - name: DATA_PATH
              value: $(workspaces.data.path)
            - name: AUTH_PATH
              value: /workspace/.docker/config.json
            - name: TRIGGER_NIGHTLY_TAG
              value: $(params.TRIGGER_NIGHTLY_TAG)
            script: |
              #!/bin/bash
              set -e

              if [[ "$TRIGGER_NIGHTLY_TAG" != "true" ]]; then
                echo "TRIGGER_NIGHTLY_TAG=$TRIGGER_NIGHTLY_TAG"
                echo "proceeding without tagging a new nightly"
                exit 0
              fi

              echo "Analyzing catalog.yaml from $CATALOG_IMAGE"
              CATALOG="$DATA_PATH"/rhods-operator/catalog.yaml
              TAG="odh-stable-nightly"

              # Step 1 & 2: Find olm.channel with name odh-stable, get the last entry name
              BUNDLE_NAME=$(yq 'select(.schema == "olm.channel" and .name == "odh-stable") | .entries[-1].name' "$CATALOG")
              echo "Bundle name: $BUNDLE_NAME"

              # Step 3: Find olm.bundle with that name, get the image
              BUNDLE_IMAGE=$(yq "select(.schema == \"olm.bundle\" and .name == \"$BUNDLE_NAME\") | .image" "$CATALOG")
              echo "Bundle image: $BUNDLE_IMAGE"

              # Step 4: Get containerImage from olm.csv.metadata property
              OPERATOR_IMAGE=$(yq "select(.schema == \"olm.bundle\" and .name == \"$BUNDLE_NAME\") | .properties[] | select(.type == \"olm.csv.metadata\") | .value.annotations.containerImage" "$CATALOG")
              echo "Operator image: $OPERATOR_IMAGE"

              # Inspect catalog image to get label and digest
              CATALOG_INSPECT=$(skopeo inspect --no-tags "docker://$CATALOG_IMAGE")
              LABEL_OPERATOR_IMAGE=$(echo "$CATALOG_INSPECT" | yq '.Labels["opendatahub-operator.image"]')
              CATALOG_DIGEST=$(echo "$CATALOG_INSPECT" | yq '.Digest')
              CATALOG_IMAGE="${CATALOG_IMAGE%:*}@${CATALOG_DIGEST}"
              echo "Catalog image: $CATALOG_IMAGE"
              echo "Operator image from catalog label: $LABEL_OPERATOR_IMAGE"

              if [ "$OPERATOR_IMAGE" != "$LABEL_OPERATOR_IMAGE" ]; then
                echo "ERROR: Operator image mismatch!"
                echo "  From catalog.yaml: $OPERATOR_IMAGE"
                echo "  From catalog label: $LABEL_OPERATOR_IMAGE"
                exit 1
              fi
              echo "Operator image verified."

              # Function to tag an image
              tag_image() {
                local IMAGE="$1"
                local TAG="$2"
                # Extract registry/repo from image (remove @sha256:...)
                local REPO="${IMAGE%@*}"
                echo "Tagging $IMAGE as $REPO:$TAG"
                skopeo copy --all --authfile "$AUTH_PATH" "docker://$IMAGE" "docker://$REPO:$TAG"
              }

              # Tag all three images as odh-stable-nightly
              echo "Tagging images as $TAG..."
              tag_image "$BUNDLE_IMAGE" "$TAG"
              tag_image "$OPERATOR_IMAGE" "$TAG"
              tag_image "$CATALOG_IMAGE" "$TAG"

              echo "Done! All images have been tagged as $TAG"
              echo "Bundle: $BUNDLE_IMAGE"
              echo "FBC: $CATALOG_IMAGE"
              echo "Operator: $OPERATOR_IMAGE"
      - name: trigger-nightly-tests
        description: trigger nightly tests
        when:
        - input: $(params.TRIGGER_NIGHTLY_TESTS)
          operator: in
          values:
          - "true"
        runAfter:
        - tag-nightly
        taskSpec:
          steps:
          - image: quay.io/rhoai/rhoai-task-toolset:odh-nightly-runner
            env:
            - name: HOME
              value: /workspace
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rhods-ci
                  key: secret
            script: |
              #!/bin/bash
              set -e

              TARGET=odh-stable

              OWNER="red-hat-data-services"
              REPO="conforma-reporter"
              WORKFLOW_FILE="smoke-trigger.yaml"

              echo "Triggering nightly jenkins jobs for: $TARGET"

              curl -f -X POST "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_FILE/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{ "ref": "main", "inputs": { "target_branch": "'"$TARGET"'" } }'
      - name: slack-notification
        description: notify slack about new nightly
        when:
        - input: $(params.TRIGGER_SLACK)
          operator: in
          values:
          - "true"
        runAfter:
        - tag-nightly
        workspaces:
        - name: data
          workspace: data
        taskSpec:
          workspaces:
          - name: data
            optional: false
          steps:
          - image: quay.io/rhoai/rhoai-task-toolset:odh-nightly-runner@sha256:c8bc1b9f04259c3cbfbfc74fc1bc143d9c0c42d8acf17ef240630719a4faa882
            env:
            - name: HOME
              value: /workspace
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rhoai-devops-bot-slack-token
                  key: SLACK_TOKEN
            - name: LATEST_CATALOG_CI_IMAGE
              value: $(tasks.choose-ci-build.results.latest-catalog-ci-image)
            - name: LATEST_BUILD_METADATA_URL
              value: $(tasks.choose-ci-build.results.latest-build-metadata-url)
            - name: BUILD_URL
              value: $(tasks.choose-ci-build.results.latest-catalog-ci-build-url)
            - name: CHANNEL
              value: C07RGA06207 # C0883L8FARE
            workingDir: /workspace
            script: |
              #!/bin/bash
              set -e
              mkdir slack && cd slack
              git init .
              git remote add origin git@github.com:red-hat-data-services/rhods-devops-infra.git
              git fetch origin main
              git fetch origin odh-tracer
              git show origin/main:tools/send-slack-message/send-slack-message.sh > ./send-slack-message.sh
              git show origin/odh-tracer:tools/tracer/tracer.sh > ./tracer.sh
              chmod +x ./send-slack-message.sh
              chmod +x ./tracer.sh

              ./tracer.sh --odh -i "$LATEST_CATALOG_CI_IMAGE" --show-commits | tee tracer-output.txt
              alertEmoji=":nightly:"
              slack_message="PROOF OF CONCEPT - DO NOT USE
              ${alertEmoji} A new *Nightly Build* is available for ODH
              Image: ${LATEST_CATALOG_CI_IMAGE}
              Build Metadata: <${LATEST_BUILD_METADATA_URL}|Link>
              Build URL: <${BUILD_URL}>"
              ./send-slack-message.sh -c "$CHANNEL" -m "$slack_message" -f tracer-output.txt -v
    workspaces:
    - name: data
      optional: false
  workspaces:
  - name: data
    emptyDir: {}
