---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: odh-pr-test-feast
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: List of components in the group
      name: group-components
      type: string
    - name: oci-artifacts-repo
      default: 'quay.io/opendatahub/kserve'
      description: The OCI container used to store all test artifacts.
    - name: artifact-browser-url
      default: 'https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/'
      description: The OCI container used to store all test artifacts.
  tasks:
    - name: generate-snapshot
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      workspaces:
      - name: basic-auth
        workspace: git-auth
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
        - name: revision
          value: odh
        - name: pathInRepo
          value: konflux-tekton-tasks/generate-snapshot-for-group-testing/0.1/generate-snapshot-for-group-testing.yaml
    - name: audit-snapshot
      runAfter:
        - generate-snapshot
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      taskSpec:
        params:
          - name: COMPONENTS
            description: List of components in the group
        results:
        - name: pull-request-author
        - name: pull-request-number
        - name: git-repo
        - name: git-org
        - name: git-revision
        steps:
          - name: audit-snapshot
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
              - name: COMPONENTS
                value: $(params.COMPONENTS)
              - name: PR_AUTHOR
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sender']
              - name: PR_NUMBER
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['pipelinesascode.tekton.dev/pull-request']
              - name: GIT_REPO
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/url-repository']
              - name: GIT_ORG
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/url-org']
              - name: GIT_REVISION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sha']
            script: |
              #!/bin/bash
              set -e
              echo "SNAPSHOT=${SNAPSHOT}"

              # Parse JSON and iterate through each component
              while IFS= read -r row; do
                  COMPONENT_NAME=$(echo "$row" | base64 -d | jq -r '.key')
                  IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
                  GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
                  GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
                  echo "${COMPONENT_NAME} IMAGE: ${IMAGE}"
                  echo "GIT_COMMIT=${GIT_COMMIT}"
                  echo "GIT_URL=${GIT_URL}"
              done < <(echo "$COMPONENTS" | jq -r 'to_entries[] | @base64')

              echo -n "${PR_AUTHOR}" > "$(results.pull-request-author.path)"
              echo -n "${PR_NUMBER}" > "$(results.pull-request-number.path)"
              echo -n "${GIT_REPO}" > "$(results.git-repo.path)"
              echo -n "${GIT_ORG}" > "$(results.git-org.path)"
              echo -n "${GIT_REVISION}" > "$(results.git-revision.path)"

#    - name: provision-eaas-space
#      runAfter:
#        - audit-snapshot
#      taskRef:
#        resolver: git
#        params:
#          - name: url
#            value: https://github.com/konflux-ci/build-definitions.git
#          - name: revision
#            value: main
#          - name: pathInRepo
#            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
#      params:
#        - name: ownerName
#          value: $(context.pipelineRun.name)
#        - name: ownerUid
#          value: $(context.pipelineRun.uid)
#    - name: provision-cluster
#      runAfter:
#        - provision-eaas-space
#      taskSpec:
#        results:
#          - name: clusterName
#            value: "$(steps.create-cluster.results.clusterName)"
#        steps:
#          - name: get-supported-versions
#            ref:
#              resolver: git
#              params:
#                - name: url
#                  value: https://github.com/konflux-ci/build-definitions.git
#                - name: revision
#                  value: main
#                - name: pathInRepo
#                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
#            params:
#              - name: eaasSpaceSecretRef
#                value: $(tasks.provision-eaas-space.results.secretRef)
#          - name: pick-version
#            ref:
#              resolver: git
#              params:
#                - name: url
#                  value: https://github.com/konflux-ci/build-definitions.git
#                - name: revision
#                  value: main
#                - name: pathInRepo
#                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
#            params:
#              - name: prefix
#                value: "$(steps.get-supported-versions.results.versions[0])."
#          - name: create-cluster
#            ref:
#              resolver: git
#              params:
#                - name: url
#                  value: https://github.com/konflux-ci/build-definitions.git
#                - name: revision
#                  value: main
#                - name: pathInRepo
#                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
#            params:
#              - name: eaasSpaceSecretRef
#                value: $(tasks.provision-eaas-space.results.secretRef)
#              - name: version
#                value: "$(steps.pick-version.results.version)"
#              - name: instanceType
#                value: m5.2xlarge
#    - name: deploy-and-test
#      runAfter:
#        - provision-cluster
#      params:
#        - name: oci-artifacts-repo
#          value: $(params.oci-artifacts-repo)
#      taskSpec:
#        volumes:
#          - name: credentials
#            emptyDir: {}
#          - name: odh-registry-secret
#            secret:
#              secretName: odh-registry-secret
#        params:
#          - name: oci-artifacts-repo
#            description: oci-artifacts-repo
#        steps:
#          - name: get-kubeconfig
#            ref:
#              resolver: git
#              params:
#                - name: url
#                  value: https://github.com/konflux-ci/build-definitions.git
#                - name: revision
#                  value: main
#                - name: pathInRepo
#                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
#            params:
#              - name: eaasSpaceSecretRef
#                value: $(tasks.provision-eaas-space.results.secretRef)
#              - name: clusterName
#                value: "$(tasks.provision-cluster.results.clusterName)"
#              - name: credentials
#                value: credentials
#          - name: deploy-and-e2e
#            image: quay.io/rhoai/rhoai-task-toolset:go-its
#            env:
#              - name: KUBECONFIG
#                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
#              - name: SNAPSHOT
#                value: $(tasks.generate-snapshot.results.SNAPSHOT)
#              - name: ARTIFACT_DIR
#                value: /workspace/artifact-dir
#            workingDir: /workspace/source
#            volumeMounts:
#              - name: credentials
#                mountPath: /credentials
#            script: |
#              oc get pods
#              oc whoami
#
#              echo "SNAPSHOT=${SNAPSHOT}"
#              COMPONENT_NAME=odh-feast-operator-ci
#              FEAST_OPERATOR_CONTROLLER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
#              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
#              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
#              echo "  FEAST_OPERATOR_CONTROLLER_IMAGE: ${FEAST_OPERATOR_CONTROLLER_IMAGE}"
#              echo "GIT_COMMIT=${GIT_COMMIT}"
#              echo "GIT_URL=${GIT_URL}"
#
#              COMPONENT_NAME=odh-feature-server-ci
#              FEAST_FEATURE_SERVER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
#              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
#              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
#              echo "  FEAST_FEATURE_SERVER_IMAGE: ${FEAST_FEATURE_SERVER_IMAGE}"
#              echo "GIT_COMMIT=${GIT_COMMIT}"
#              echo "GIT_URL=${GIT_URL}"
#
#              REPO_URL=${GIT_URL}
#              REVISION=${GIT_COMMIT}
#
#              echo "REPO_URL=${REPO_URL}"
#              echo "REVISION=${REVISION}"
#              git clone "${REPO_URL}" src_code
#              cd src_code
#              git checkout ${REVISION}
#
#              export RUN_ON_OPENSHIFT_CI=true
#              cd infra/feast-operator
#              make install && make deploy IMG=${FEAST_OPERATOR_CONTROLLER_IMAGE} FS_IMG=${FEAST_FEATURE_SERVER_IMAGE}
#              oc wait --for condition=Available -n feast-operator-system deployment feast-operator-controller-manager
#              make test-e2e
#              make undeploy IMG=${FEAST_OPERATOR_CONTROLLER_IMAGE} FS_IMG=${FEAST_FEATURE_SERVER_IMAGE}
#
#              make test-previous-version
#              oc delete deployment feast-operator-controller-manager -n feast-operator-system
#
#              make test-upgrade
#
#              # cd ${ARTIFACT_DIR}
#
#              # feast-must-gather
#              oc adm must-gather --image=quay.io/modh/must-gather:rhoai-2.24 --dest-dir "${ARTIFACT_DIR}/gather-feast" -- "export COMPONENT=feastoperator; /usr/bin/gather"
#
#              # openshift-must-gather
#              oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
#

#    - name: generate-artifacts
#      runAfter:
#        - audit-snapshot
#      taskSpec:
#        volumes:
#          - name: odh-registry-secret
#            secret:
#              secretName: odh-registry-secret
#        steps:
#          - name: generate-snapshot
#            image: quay.io/konflux-ci/konflux-test:stable
#            workingDir: /workspace
#            env:
#              - name: ARTIFACT_DIR
#                value: /workspace/artifact-dir
#            script: |
#              #!/bin/bash
#              set -e
#              mkdir -p ${ARTIFACT_DIR}
#              echo "generating the dummy test logs 1" > ${ARTIFACT_DIR}/logs1.txt
#              echo "generating the dummy test logs 2" > ${ARTIFACT_DIR}/logs2.txt
#
#          - name: secure-push-oci
#            ref:
#              resolver: git
#              params:
#                - name: url
#                  value: https://github.com/konflux-ci/tekton-integration-catalog.git
#                - name: revision
#                  value: main
#                - name: pathInRepo
#                  value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
#            params:
#              - name: workdir-path
#                value: /workspace/artifact-dir
#              - name: oci-ref
#                value: $(params.oci-artifacts-repo):$(context.pipelineRun.name)
#              - name: credentials-volume-name
#                value: odh-registry-secret
  finally:
  - name: pull-request-status-message
    taskRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
        - name: revision
          value: odh
        - name: pathInRepo
          value: konflux-tekton-tasks/pull-request-comment/0.1/pull-request-comment.yaml
    params:
      - name: test-name
        value: $(context.pipelineRun.name)
      - name: oci-container
        value: $(params.oci-artifacts-repo):$(context.pipelineRun.name)
      - name: pipeline-aggregate-status
        value: $(tasks.status)
      - name: pull-request-author
        value: $(tasks.audit-snapshot.results.pull-request-author)
      - name: pull-request-number
        value: $(tasks.audit-snapshot.results.pull-request-number)
      - name: git-repo
        value: $(tasks.audit-snapshot.results.git-repo)
      - name: git-org
        value: $(tasks.audit-snapshot.results.git-org)
      - name: git-revision
        value: $(tasks.audit-snapshot.results.git-revision)
      - name: artifact-browser-url
        value: $(params.artifact-browser-url)
  workspaces:
  - name: git-auth
    optional: true
