---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: odh-pr-test
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: List of components in the group
      name: group-components
      type: string
  tasks:
    - name: generate-snapshot
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      workspaces:
      - name: basic-auth
        workspace: git-auth
      taskSpec:
        params:
          - name: COMPONENTS
            description: List of components in the group
        results:
        - description: Snapshot json string
          name: SNAPSHOT
        workspaces:
          - name: basic-auth
            optional: true
        steps:
          - name: generate-snapshot
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: COMPONENTS
                value: $(params.COMPONENTS)
              - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
                value: $(workspaces.basic-auth.bound)
              - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
                value: $(workspaces.basic-auth.path)
            script: |
              #!/bin/bash
              set -e
              json_string="$COMPONENTS"
              echo ${COMPONENTS}
              # Tag to search for
              TAG="odh-pr"

              # Temporary file to store results
              temp_file=$(mktemp)
              echo "{}" > "$temp_file"

              # Parse JSON and iterate through each component
              while IFS= read -r row; do
                  # Decode the base64 encoded row
                  component=$(echo "$row" | base64 -d | jq -r '.key')
                  repo_path=$(echo "$row" | base64 -d | jq -r '.value')

                  # Construct full quay URL
                  full_repo="quay.io/${repo_path}"

                  echo "Processing component: $component" >&2
                  echo "Repository: $full_repo" >&2

                  # Extract namespace and repository name from repo_path
                  # Format: namespace/project/repository
                  namespace=$(echo "$repo_path" | cut -d'/' -f1-2)
                  repository=$(echo "$repo_path" | cut -d'/' -f3)

                  # Query Quay API to get the digest for the tag
                  api_url="https://quay.io/api/v1/repository/${namespace}/${repository}/tag/?specificTag=${TAG}"

                  echo "Querying: $api_url" >&2

                  # Make API request and extract the manifest digest
                  response=$(curl -s "$api_url")

                  # Get the latest (first) tag's manifest digest
                  manifest_digest=$(echo "$response" | jq -r '.tags[0].manifest_digest // empty')

                  if [ -z "$manifest_digest" ]; then
                      echo "Warning: No digest found for $component with tag $TAG" >&2
                      full_image_uri="${full_repo}:${TAG}"
                      git_url=""
                      git_commit=""
                  else
                      echo "Found digest: $manifest_digest" >&2
                      full_image_uri="${full_repo}@${manifest_digest}"

                      # Query Quay API to get the manifest details and extract labels
                      manifest_api_url="https://quay.io/api/v1/repository/${namespace}/${repository}/manifest/${manifest_digest}"
                      echo "Querying manifest: $manifest_api_url" >&2

                      manifest_response=$(curl -s "$manifest_api_url")
                      echo "manifest_response=${manifest_response}" >&2

                      # Check if this is a manifest list (multi-arch image)
                      is_manifest_list=$(echo "$manifest_response" | jq -r '.is_manifest_list // false')
                      echo "Is manifest list: $is_manifest_list" >&2

                      if [ "$is_manifest_list" = "true" ]; then
                          echo "Multi-arch image detected, extracting first manifest digest" >&2

                          # Get the digest of the first manifest in the list
                          first_manifest_digest=$(echo "$manifest_response" | jq -r '.manifest_data' | jq -r '.manifests[0].digest // empty')

                          if [ -z "$first_manifest_digest" ]; then
                              echo "Warning: No manifest found in manifest list" >&2
                              git_url=""
                              git_commit=""
                          else
                              echo "First manifest digest: $first_manifest_digest" >&2

                              # Query API again with the specific manifest digest
                              specific_manifest_api_url="https://quay.io/api/v1/repository/${namespace}/${repository}/manifest/${first_manifest_digest}/labels"
                              echo "Querying specific manifest: $specific_manifest_api_url" >&2

                              specific_manifest_response=$(curl -s "$specific_manifest_api_url")
                              echo "specific_manifest_response=${specific_manifest_response}"
                              # Extract git.url and git.commit labels from the specific manifest
                              git_url=$(echo "$specific_manifest_response" | jq -r '.labels[] | select(.key == "git.url") | .value// empty')
                              git_commit=$(echo "$specific_manifest_response" | jq -r '.labels[] | select(.key == "git.commit") | .value// empty')
                          fi
                      else
                          echo "Single-arch image, extracting labels directly" >&2

                          # Extract git.url and git.commit labels from current manifest
                          git_url=$(echo "$manifest_response" | jq -r '.config.config.Labels["git.url"] // empty')
                          git_commit=$(echo "$manifest_response" | jq -r '.config.config.Labels["git.commit"] // empty')
                      fi

                      echo "Git URL: $git_url" >&2
                      echo "Git Commit: $git_commit" >&2
                  fi

                  # Add to output JSON with image URI, git.url, and git.commit
                  jq --arg key "$component" \
                     --arg image "$full_image_uri" \
                     --arg giturl "$git_url" \
                     --arg gitcommit "$git_commit" \
                     '. + {($key): {image: $image, "git.url": $giturl, "git.commit": $gitcommit}}' \
                     "$temp_file" > "${temp_file}.tmp" && mv "${temp_file}.tmp" "$temp_file"

                  echo "" >&2
              done < <(echo "$json_string" | jq -r 'to_entries[] | @base64')

              # Print final output JSON
              echo "Output JSON:" >&2
              cat "$temp_file" | jq '.'
              echo -en $(cat "$temp_file") > "$(results.SNAPSHOT.path)"
              # Cleanup
              rm -f "$temp_file"
    - name: test-snapshot
      runAfter:
        - generate-snapshot
      taskSpec:
        steps:
          - name: test-snapshot
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
            script: |
              #!/bin/bash
              set -e
              echo "SNAPSHOT=${SNAPSHOT}"
              COMPONENT_NAME=odh-feast-operator-ci
              FEAST_OPERATOR_CONTROLLER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
              echo "  FEAST_OPERATOR_CONTROLLER_IMAGE: ${FEAST_OPERATOR_CONTROLLER_IMAGE}"
              echo "GIT_COMMIT=${GIT_COMMIT}"
              echo "GIT_URL=${GIT_URL}"

              COMPONENT_NAME=odh-feature-server-ci
              FEAST_FEATURE_SERVER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
              echo "  FEAST_FEATURE_SERVER_IMAGE: ${FEAST_FEATURE_SERVER_IMAGE}"
              echo "GIT_COMMIT=${GIT_COMMIT}"
              echo "GIT_URL=${GIT_URL}"
    - name: provision-eaas-space
      runAfter:
        - test-snapshot
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
#      when:
#        - input: "$(tasks.check-prerequisites.results.event-type)"
#          operator: in
#          values: ["pull_request", "retest-all-comment", "on-comment"]
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.2xlarge
#      when:
#        - input: "$(tasks.check-prerequisites.results.event-type)"
#          operator: in
#          values: ["pull_request", "retest-all-comment", "on-comment"]
    - name: deploy-and-test
      runAfter:
        - provision-cluster
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: deploy-and-e2e
            image: quay.io/rhoai/rhoai-task-toolset:go-its
            env:
              - name: KUBECONFIG
                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
            workingDir: /workspace/source
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              oc get pods
              oc whoami

              echo "SNAPSHOT=${SNAPSHOT}"
              COMPONENT_NAME=feast-operator-poc
              FEAST_OPERATOR_CONTROLLER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
              echo "  FEAST_OPERATOR_CONTROLLER_IMAGE: ${FEAST_OPERATOR_CONTROLLER_IMAGE}"
              echo "GIT_COMMIT=${GIT_COMMIT}"
              echo "GIT_URL=${GIT_URL}"

              COMPONENT_NAME=feature-server-poc
              FEAST_FEATURE_SERVER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
              GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
              GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
              echo "  FEAST_FEATURE_SERVER_IMAGE: ${FEAST_FEATURE_SERVER_IMAGE}"
              echo "GIT_COMMIT=${GIT_COMMIT}"
              echo "GIT_URL=${GIT_URL}"

              REPO_URL=${GIT_URL}
              REVISION=${GIT_COMMIT}

              echo "REPO_URL=${REPO_URL}"
              echo "REVISION=${REVISION}"
              git clone "${REPO_URL}" src_code
              cd src_code
              git checkout ${REVISION}

              export RUN_ON_OPENSHIFT_CI=true
              cd infra/feast-operator
              make install && make deploy IMG=${FEAST_OPERATOR_CONTROLLER_IMAGE} FS_IMG=${FEAST_FEATURE_SERVER_IMAGE}
              oc wait --for condition=Available -n feast-operator-system deployment feast-operator-controller-manager
              make test-e2e
              make undeploy IMG=${FEAST_OPERATOR_CONTROLLER_IMAGE} FS_IMG=${FEAST_FEATURE_SERVER_IMAGE}

              make test-previous-version
              oc delete deployment feast-operator-controller-manager -n feast-operator-system

              make test-upgrade
  workspaces:
  - name: git-auth
    optional: true
