---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac-no-mr
    mintmaker.appstudio.redhat.com/disabled: true
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
  name: odh-codeflare-operator
spec:
  application: opendatahub-release
  componentName: odh-codeflare-operator
  containerImage: quay.io/opendatahub/odh-codeflare-operator
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      url: https://github.com/opendatahub-io/codeflare-operator.git
