---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: opendatahub-operator-e2e-test-scenario
  namespace: open-data-hub-tenant
spec:
  application: opendatahub-release
  contexts:
  - description: execute the integration test when component odh-operator updates
    name: component_odh-operator
  resolverRef:
    params:
    - name: org
      value: opendatahub-io
    - name: repo
      value: odh-konflux-central
    - name: serverURL
      value: https://github.com
    - name: revision
      value: main
    - name: pathInRepo
      value: integration-tests/opendatahub-operator/e2e-test.yaml
    - name: token
      value: github-token-secret
    - name: tokenKey
      value: token
    resolver: git
    resourceKind: pipeline
