name: Build Integration Test Images

on:
  push:
    paths:
      - "integration-tests/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect changed Dockerfiles
        id: changes
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'integration-tests/.*/Dockerfile\.' || true)

          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "Changed Dockerfiles:"
          echo "$FILES"

      - name: Login to Quay
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Build and Push Images
        if: steps.changes.outputs.files != ''
        run: |
          for file in ${{ steps.changes.outputs.files }}
          do
            TAG=$(basename $file | cut -d'.' -f2)
            DIR=$(dirname $file)

            echo "Building quay.io/rhoai/rhoai-task-toolset:$TAG"

            docker build -f $file -t quay.io/rhoai/rhoai-task-toolset:$TAG $DIR
            docker push quay.io/rhoai/rhoai-task-toolset:$TAG
          done
